const projects = [
    {
        title: "ReLeaf",
        description: "Environmental platform for sustainability",
        gifUrl: "https://cdn.dribbble.com/userupload/29805678/file/original-82f5c5c9f3f89350d921336df6d5e552.gif",
        demo: "https://releaf-store.vercel.app",
        github: "https://github.com/armanulhaq/releaf",
    },
    {
        title: "Wanderly",
        description: "Travel planning and exploration app",
        gifUrl: "https://cdn.dribbble.com/userupload/22229123/file/original-a21a72a76f11c88c4695974e814fbedc.gif",
        demo: "https://wanderly-trips.onrender.com",
        github: "https://github.com/armanulhaq/wanderly",
    },
    {
        title: "NotePilot",
        description: "Smart note-taking application",
        gifUrl: "https://cdn.dribbble.com/userupload/22551256/file/original-6d254c20fcfdd25e9a4f8958e3b438cd.gif",
        demo: "https://notepilot-2.onrender.com",
        github: "https://github.com/armanulhaq/NotePilot",
    },
    {
        title: "Sahyog",
        description: "Donation management system",
        gifUrl: "https://cdn.dribbble.com/userupload/39295694/file/original-f47f421d3bf08ed2057d0152dc6f460c.gif",
        demo: "https://donate-with-sahyog.onrender.com",
        github: "https://github.com/armanulhaq/donate-with-sahyog",
    },
    {
        title: "HopeSprout",
        description: "Social impact initiative tracker",
        gifUrl: "https://cdn.dribbble.com/userupload/22189168/file/original-ff83139b09e1c0a6099e5d8238f40980.gif",
        demo: "https://hopesprout.onrender.com",
        github: "https://github.com/armanulhaq/NGO",
    },
    {
        title: "Zapp",
        description: "Instant messaging app",
        gifUrl: "https://cdn.dribbble.com/userupload/40727666/file/original-37f9059c9fccc73bdc11ded550d5c3c7.gif",
        demo: "https://zapp-lime.vercel.app/",
        github: "https://github.com/armanulhaq/Zapp",
    },
    {
        title: "LitPick",
        description: "Book recommendation engine",
        gifUrl: "https://cdn.dribbble.com/userupload/23941634/file/original-674353314a72b96389e4ccc6a0a47021.gif",
        demo: "https://litpickai.vercel.app/",
        github: "https://github.com/armanulhaq/litpickai",
    },
    {
        title: "Eat Fusion",
        description: "Food delivery platform",
        gifUrl: "https://cdn.dribbble.com/userupload/21537816/file/original-d1df206da258b0eccc1049c7ea44b29d.gif",
        demo: "https://eat-fusion.vercel.app/",
        github: "https://github.com/armanulhaq/eat-fusion",
    },
    {
        title: "Sushimanoo",
        description: "Restaurant ordering system",
        gifUrl: "https://cdn.dribbble.com/userupload/20805250/file/original-2dcadf6a2c0741f384255b4e534271b3.gif",
        demo: "https://sushi-ruby-seven.vercel.app/",
        github: "https://github.com/armanulhaq/sushi",
    },
    {
        title: "Alcami",
        description: "3D interactive experience",
        gifUrl: "https://cdn.dribbble.com/userupload/24898076/file/original-0e6fdb1ed026c5d0c908737a6dbfdb42.gif",
        demo: "https://cube-delta-ten.vercel.app/",
        github: "https://github.com/armanulhaq/cube",
    },
    {
        title: "Fusion Store",
        description: "E-commerce platform",
        gifUrl: "https://cdn.dribbble.com/users/97870/screenshots/1425320/media/676d206f27d9808d168887791efc4b5e.gif",
        demo: "https://fusion-store.vercel.app/",
        github: "https://github.com/armanulhaq/fusion-store",
    },
    {
        title: "Motion Detection",
        description: "Computer vision project",
        gifUrl: "https://cdn.dribbble.com/users/224485/screenshots/1932553/media/9ae59c34effbc06ac79c8e8a97d87461.gif",
        github: "https://github.com/armanulhaq/camera-alert",
    },
    {
        title: "University Website",
        description: "Educational institution portal",
        gifUrl: "https://cdn.dribbble.com/users/808936/screenshots/3232987/media/fb181b09abf9419fe9200207b1c35a47.gif",
        demo: "https://fusionuniversity.vercel.app/",
        github: "https://github.com/armanulhaq/fusion-university",
    },
    {
        title: "Weather Forecast",
        description: "Real-time weather application",
        gifUrl: "https://cdn.dribbble.com/users/28455/screenshots/1389791/media/bd9f8d16f8a3027d4dccb852d44b37d6.gif",
        demo: "https://armanulhaq-weather-dashboard-main-gxdudm.streamlit.app/",
        github: "https://github.com/armanulhaq/weather-dashboard",
    },
];

export default projects;
